# Generated by Django 6.0.6 on 2026-07-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('date_inventory', models.DateField()),
                ('date_disposal', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('repair', 'Under Repair'), ('disposed', 'Disposed'), ('lost', 'Lost')], default='available', max_length=20)),
                ('defect_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
