# Generated by Django 6.0.6 on 2026-07-08 06:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('added', 'Added'), ('edited', 'Edited'), ('deleted', 'Deleted'), ('uploaded', 'Uploaded')], max_length=20)),
                ('item_type', models.CharField(max_length=100)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('performed_by', models.CharField(default='System', max_length=150)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
