# Generated by Django 6.0.6 on 2026-07-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
