# Generated by Django 6.0.6 on 2026-07-09 05:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('added', 'Added'), ('edited', 'Edited'), ('deleted', 'Deleted'), ('uploaded', 'Uploaded'), ('borrowed', 'Borrowed'), ('returned', 'Returned')], max_length=20),
        ),
        migrations.CreateModel(
            name='IssuanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_borrowed', models.PositiveIntegerField(default=1)),
                ('borrower_name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('office_location', models.CharField(max_length=150)),
                ('contact_number', models.CharField(blank=True, max_length=30, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('issued_by', models.CharField(max_length=150)),
                ('date_issued', models.DateField(default=django.utils.timezone.now)),
                ('expected_return', models.DateField()),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='borrowed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('inventory_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuances', to='inventory.inventory')),
            ],
            options={
                'ordering': ['-date_issued'],
            },
        ),
    ]
