# Generated by Django 6.0.6 on 2026-07-09 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_auditlog_action_issuancelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuancelog',
            old_name='contact_number',
            new_name='tel_no',
        ),
        migrations.RemoveField(
            model_name='issuancelog',
            name='department',
        ),
    ]
